

"""a,b=10,0
try: #it is an exception handling code used when we know there a error could happen
    c=a/b
    print(c)
except ZeroDivisionError: # this "except' is used when a zero exception is occourd
    print("pls enter the correct value ")
except NameError:
    print(" program is exicuted")
except Exception:

    print("erorr"""

"""while True:
    try:
        a,b=map(int,input("enter two numbers: ").split())
        c=a/b
        print(c)
        break
    except ZeroDivisionError:
        print("enter a valid number ")
    except Exception:
        print("error")
    else:
        print("no errors")
    finally:
        print("ellam seriyayiii")"""




